aoc/alsa: updates to snd_soc_card_jack_new()
Upstream renamed snd_soc_card_jack_new() to snd_soc_card_jack_new_pins()
in commit 9aed2d6cdb7 ("ASoC: soc-card: Create jack kcontrol without
pins"). Make the corresponding update here and fix the following issue:

alsa/aoc_alsa_card.c:1712:33: error: too many arguments to function call, expected 4, have 6
                SND_JACK_BTN_3, &pdata->jack,   NULL, 0);
                                                ^~~~~~~

Bug: 236216026
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I470c382fdecbb5f05d2275f4ffe95d0dad7dba51